export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const REMOVE_ALL_INGREDIENTS = 'REMOVE_ALL_INGREDIENTS';

export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const ORDER_DETAILS = 'ORDER_DETAILS';
