export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const REMOVE_ALL_INGREDIENTS = 'REMOVE_ALL_INGREDIENTS';
export const LOAD_DATA_REORDER = 'LOAD_DATA_REORDER';

export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const ADD_ORDER_DETAILS = 'ADD_ORDER_DETAILS';
export const REMOVE_ORDER_DETAILS = 'REMOVE_ORDER_DETAILS';
