
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checking out master parmesanio
      uses: actions/checkout@master

    - name: Setting up Node parmesanio
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'
        
    - name: Starting parmesanio scripts
      run: |
        npm install
        git config --global user.email "abasolojohnjourish@gmail.com"
        git config --global user.name ${GHPAGES_DEPLOY_USERNAMIO}
        git remote rm origin
        git remote add origin https://${GHPAGES_DEPLOY_USERNAMIO}:${GHPAGES_DEPLOY_PARMESANIO}@github.com/${GHPAGES_DEPLOY_USERNAMIO}/project.git
        npm run deploy
      env:
        GHPAGES_DEPLOY_PARMESANIO: ${{ secrets.GHPAGES_DEPLOY_PARMESANIO }}
        GHPAGES_DEPLOY_USERNAMIO: jjdcabasolo
