
# action taken from: https://github.com/peaceiris/actions-gh-pages
name: [Deployment] Automated GitHub Pages deployment on master push

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: build
      uses: actions/setup-node@v1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        node-version: '10.16'
    - run: |
        npm install
        npm run build
        
